// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"be-lab/dal"
	"be-lab/server"
	"be-lab/service"
)

// Injectors from wire.go:

func InitServer() *server.Server {
	dalDal := dal.NewDal()
	serviceService := service.NewService(dalDal)
	serverServer := server.NewServer(serviceService)
	return serverServer
}
